# Generated by Django 3.1.5 on 2021-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.CharField(default='', max_length=24)),
                ('value', models.CharField(default='', max_length=10)),
                ('aim', models.CharField(default='', max_length=300)),
                ('textBooking', models.CharField(default='', max_length=300)),
                ('customer', models.CharField(default='', max_length=300)),
                ('blz', models.CharField(max_length=14)),
                ('creditorId', models.CharField(default='', max_length=40)),
                ('mandat', models.CharField(default='', max_length=40)),
                ('customerReference', models.CharField(default='', max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
