# Generated by Django 3.1.5 on 2021-04-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCredior', models.CharField(max_length=60)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=24)),
                ('credtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.creditor')),
            ],
        ),
        migrations.AddField(
            model_name='creditor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.project'),
        ),
    ]
