# Generated by Django 3.1.5 on 2021-04-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credtor',
            new_name='creditor',
        ),
    ]
