# Generated by Django 3.1.5 on 2021-04-30 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_auto_20210430_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='dateUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='firstTransact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='lastTransact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='nrTransactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creditorId',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customerReference',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mandat',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='textBooking',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='types',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verwendungszweck',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='', max_length=24),
        ),
    ]
